IPASS Stephan Zaaijer: IPASS::RF24L01 Class Reference
IPASS::RF24L01 Class Reference
Class for the RF24L01.
#include <RF24L01.hpp>
Classes
class COMMAND
SUBCLASS COMMAND.
class REGISTER
SUBCLASS REGISTER.
class SETTING
SUBCLASS SETTING.
Public Member Functions
RF24L01 (hwlib::spi_bus_bit_banged_sclk_mosi_miso &bus, hwlib::pin_out &modusPin, hwlib::pin_out &minion_select, hwlib::pin_in &IRQ, std::array< uint8_t, 5 > RX_ADDR_P0, std::array< uint8_t, 5 > TX_ADDR, uint8_t channel=0x02, bool datarate=true, bool CRC=true, bool CRC_width=true)
Default constructor for RF24L01.
void change_ADDR (const uint8_t &register_address, const std::array< uint8_t, 5 > &address_value)
function to change to value in the address-register
void change_arc (uint8_t arc)
Change the arc value in the SETUP_RETR-register.
void change_ard (uint8_t ard)
Change the ard value in the SETUP_RETR-register.
void change_aw (uint8_t aw)
Change the aw value in the SETUP_AW-register.
void change_rf_pwr (uint8_t rf_pwr)
Change the rf_pwr value in the RF_SETUP-register.
void change_RX_PW_P (const uint8_t &pipe, const uint8_t &value)
change the amount of bytes in the specified RX_pipes
void flush_rx_tx ()
function flush the RX and TX payload registers
bool packet_recieved ()
boolean to check if a packet is recieved
bool packet_send ()
boolean that checks if a packet is send
template<size_t amount>
void read_rx (std::array< uint8_t, amount > &Data)
Function to read recieved packages.
template<size_t amount>
void register_read (const uint8_t &address, std::array< uint8_t, amount > &data_out)
Function to read multiple uint8_t value from an register.
uint8_t register_read (const uint8_t &address)
Function to read a uint8_t value from an register.
void register_read (const uint8_t &address, uint8_t &data_out)
Function to read a uint8_t value from an register.
void register_write (const uint8_t &address, const uint8_t &value)
function to write an value to an address
void reset_arc ()
resets the arc value to it's default value '0x03'
void reset_ard ()
resets the ard value to it's default value '0000'
void reset_aw ()
resets the aw value to it's default value '11'
void reset_rf_pwr ()
resets the rf_pwr value to it's default value '0x02'
void reset_RX_PW_P (const uint8_t &pipe)
resets the amount of bytes in RX_pipe
void send_packages ()
function that transmits the packages stored in the transmitbuffer
void set_channel (uint8_t channel)
function to change the RF-channel of the RF24L01
void setting_disable (SETTING::Setting registerFunction)
Function to enable a setting.
void setting_enable (SETTING::Setting registerFunction)
Function to enable a setting.
bool setting_read (SETTING::Setting registerFunction)
Function to read the current status if a setting.
void setting_reset (SETTING::Setting registerFunction)
Function to reset a setting.
void start_RX ()
function to start the recieving mode on the RF24L01
void stop_RX ()
function to stop the recieving mode on the RF24L01
bool test ()
Test function.
void write_command (const uint8_t &command)
Write one single command without value to the RF24L01.
template<size_t amount>
void write_tx (std::array< uint8_t, amount > &Data, bool no_ack=false)
Function to write data to TX_PLD.
Private Member Functions
template<size_t amount>
void read (const uint8_t &address, std::array< uint8_t, amount > &data_out)
Private read function.
uint8_t read (const uint8_t &address)
Private read function.
void read (const uint8_t &address, uint8_t &data_out)
Private read function.
void start_up (std::array< uint8_t, 5 > RX_ADDR_P0, std::array< uint8_t, 5 > TX_ADDR, uint8_t channel, bool CRC, bool CRC_width, bool datarate)
Startup function.
template<size_t amount>
void write (const uint8_t &command, const std::array< uint8_t, amount > &value)
Private write function.
void write (const uint8_t &command, const uint8_t &value)
Private write function.
Private Attributes
hwlib::spi_bus_bit_banged_sclk_mosi_miso & bus
SPI-Bus to read and write to the chip.
hwlib::pin_out & minion_select
hwlib::pin_out object which contains the pin connected to CSN pin of the RF24L01
hwlib::pin_out & CE_pin
hwlib::pin_out object which contains the pin connected to CE pin of the RF24L01
hwlib::pin_in & IRQ
hwlib::pin_in object which contains the pin connected to IRQ pin of the RF24L01
bool Active = false
Detailed Description
Class for the RF24L01.
Class that contains all the functions, variabeles and subclasses for the RF24L01
Constructor & Destructor Documentation
RF24L01()
IPASS::RF24L01::RF24L01 (hwlib::spi_bus_bit_banged_sclk_mosi_miso & bus, hwlib::pin_out & modusPin, hwlib::pin_out & minion_select, hwlib::pin_in & IRQ, std::array< uint8_t, 5 > RX_ADDR_P0, std::array< uint8_t, 5 > TX_ADDR, uint8_t channel = 0x02, bool datarate = true, bool CRC = true, bool CRC_width = true)
Default constructor for RF24L01.
Default constructor for the RF24L01
Parameters
bus hwlib::spi_bus_bit_banged_sclk_mosi_miso object that contains the spi_bus for the RF24L01
modusPin hwlib::pin_out object that controls the CE-pin of the RF24L01
minion_select hwlib::pin_out object that controls the Chip select of the RF24L01
IRQ hwlib::pin_out object that is connected to IRQ-pin of the RF24L01
RX_ADDR_P0 std::array<uint8_t, 5> that contains the RX-address of pipe 0
TX_ADDR std::array<uint8_t, 5> that contains the TX-address of the RF24L01
channel uint8_t which sets the rf-channel of the RF24L01
datarate boolean that controls if setup with datarate of 1 or 2 Mbps
CRC boolean that controls of CRC is enabled or disabled
CRC_width that controls of CRC is 1 or 2 bytes
References register_read(), IPASS::RF24L01::REGISTER::SETUP_AW, and start_up().
Member Function Documentation
change_ADDR()
void IPASS::RF24L01::change_ADDR (const uint8_t & register_address, const std::array< uint8_t, 5 > & address_value)
function to change to value in the address-register
if register is pipe 2 - 5 only last byte is written, first 4 bytes are the 4 most significant bytes of pipe 1
Parameters
register_address uint8_t value that contains the address of the register
address_value std::array<uint8_t, 5> that contains the new address
References IPASS::RF24L01::REGISTER::RX_ADDR_P0, IPASS::RF24L01::REGISTER::RX_ADDR_P1, IPASS::RF24L01::REGISTER::TX_ADDR, and write().
change_arc()
void IPASS::RF24L01::change_arc (uint8_t arc)
Change the arc value in the SETUP_RETR-register.
Change the arc value to value in parameter arc possible value and meanings are:
'0x00': Re-Transmit disabled
'0x01': Up to 1 Re-Transmit on fail of AA
'0x02': Up to 2 Re-Transmits on fail of AA
'0x03': Up to 3 Re-Transmits on fail of AA
'0x04': Up to 4 Re-Transmits on fail of AA
'0x05': Up to 5 Re-Transmits on fail of AA
'0x06': Up to 6 Re-Transmits on fail of AA
'0x07': Up to 7 Re-Transmits on fail of AA
'0x08': Up to 8 Re-Transmits on fail of AA
'0x09': Up to 9 Re-Transmits on fail of AA
'0x0A': Up to 10 Re-Transmits on fail of AA
'0x0B': Up to 11 Re-Transmits on fail of AA
'0x0C': Up to 12 Re-Transmits on fail of AA
'0x0D': Up to 13 Re-Transmits on fail of AA
'0x0E': Up to 14 Re-Transmits on fail of AA
'0x0F': Up to 15 Re-Transmits on fail of AA
Parameters
arc uint8_t thats written as the new value for arc
References register_read(), register_write(), and IPASS::RF24L01::REGISTER::SETUP_RETR.
change_ard()
void IPASS::RF24L01::change_ard (uint8_t ard)
Change the ard value in the SETUP_RETR-register.
Change the ard value to value in parameter ard possible value and meanings are:
'0x00': Wait 250 μS
'0x01': Wait 500 μS
'0x02': Wait 750 μS
'0x03': Wait 1000 μS
'0x04': Wait 1250 μS
'0x05': Wait 1500 μS
'0x06': Wait 1750 μS
'0x07': Wait 2000 μS
'0x08': Wait 2250 μS
'0x09': Wait 2500 μS
'0x0A': Wait 2750 μS
'0x0B': Wait 3000 μS
'0x0C': Wait 3250 μS
'0x0D': Wait 3500 μS
'0x0E': Wait 3750 μS
'0x0F': Wait 4000 μS (Delay defined from end of a transmission to start of next transmission)
Parameters
ard uint8_t thats written as the new value for ard
References register_read(), register_write(), and IPASS::RF24L01::REGISTER::SETUP_RETR.
change_aw()
void IPASS::RF24L01::change_aw (uint8_t aw)
Change the aw value in the SETUP_AW-register.
Change the aw value to value in parameter aw possible value and meanings are:
'01': 3 bytes
'10': 4 bytes
'11': 5 bytes the least significant byte is used for the address if address is less than 5 bytes
Parameters
aw uint8_t thats written as the new value for aw
References register_read(), register_write(), and IPASS::RF24L01::REGISTER::SETUP_AW.
change_rf_pwr()
void IPASS::RF24L01::change_rf_pwr (uint8_t rf_pwr)
Change the rf_pwr value in the RF_SETUP-register.
Change the rf_pwr value to value in parameter rf_pwr possible value and meanings are:
'0x00': -18 dBm
'0x01': -12 dBm
'0x02': -6 dBm
'0x03': 0 dBm
Parameters
rf_pwr uint8_t thats written as the new value for rf_pwr
References register_read(), register_write(), and IPASS::RF24L01::REGISTER::RF_SETUP.
change_RX_PW_P()
void IPASS::RF24L01::change_RX_PW_P (const uint8_t & pipe, const uint8_t & value)
change the amount of bytes in the specified RX_pipes
Parameters
pipe value 0-5 that indicates which pipes value is changed
value value 0-32 which indicates the amount of bytes in RX_payload on the specified pipe
References register_write().
packet_recieved()
bool IPASS::RF24L01::packet_recieved ()
boolean to check if a packet is recieved
Returns
boolean value that indicates if there is a packet by reading the RX_EMPTY bit in register FIFO_STATUS
References IPASS::RF24L01::SETTING::RX_EMPTY, and setting_read().
packet_send()
bool IPASS::RF24L01::packet_send ()
boolean that checks if a packet is send
Returns
boolean value that indicates if there is a packet has been send by reading the TX_EMPTY bit in register FIFO_STATUS
References setting_read(), and IPASS::RF24L01::SETTING::TX_EMPTY.
read() [1/3]
uint8_t IPASS::RF24L01::read (const uint8_t & address) private
Private read function.
Write function that writes the command and the value
Parameters
address uint8_t that contains the register-adress
Returns
returns the uint8_t that read from the register
References bus, and minion_select.
read() [2/3]
template<size_t amount> void IPASS::RF24L01::read (const uint8_t & address, std::array< uint8_t, amount > & data_out) inline private
Private read function.
Read function that writes the command and than reads the same amount of byts as the length of value
Template Parameters
amount variabele that controls the size of std::array Data
Parameters
address uint8_t that contains the SPI-command
data_out std::array uint8_t of variabel size thats read after the SPI-command
References bus, and minion_select.
read() [3/3]
void IPASS::RF24L01::read (const uint8_t & address, uint8_t & data_out) private
Private read function.
Write function that writes the command and the value
Parameters
address uint8_t that contains the register-adress
data_out uint8_t thats read after the SPI-command
References bus, and minion_select.
read_rx()
template<size_t amount> void IPASS::RF24L01::read_rx (std::array< uint8_t, amount > & Data) inline
Function to read recieved packages.
Template Parameters
amount variabele that controls the size of std::array Data
Parameters
Data std::array uint8_t that read from the RX_PLD register
Returns
returns an std::array of variabel size stored in parameter Data
References IPASS::RF24L01::COMMAND::R_RX_PAYLOAD, and read().
register_read() [1/3]
uint8_t IPASS::RF24L01::register_read (const uint8_t & address)
Function to read a uint8_t value from an register.
Function to read one uint8_t from an register
Parameters
address uint8_t which contains the address of the register
Returns
the function returns a uint8_t
References read().
register_read() [2/3]
template<size_t amount> void IPASS::RF24L01::register_read (const uint8_t & address, std::array< uint8_t, amount > & data_out) inline
Function to read multiple uint8_t value from an register.
Function to read an variabele amount of value from an register
Template Parameters
amount variabele that controls the size of std::array Data
Parameters
address uint8_t that contains the location of the register
data_out std::array of uint8_t that contains an variabel amount of values to read from the register
Returns
the function returns a std::array of variabel size stored in parameter data_out
References read().
register_read() [3/3]
void IPASS::RF24L01::register_read (const uint8_t & address, uint8_t & data_out)
Function to read a uint8_t value from an register.
Function to read one uint8_t from an register
Parameters
address uint8_t which contains the address of the register
data_out uint8_t in which the output of register read is stored
Returns
the function returns a uint8_t stored in parameter data_out
References read().
register_write()
void IPASS::RF24L01::register_write (const uint8_t & address, const uint8_t & value)
function to write an value to an address
function to write an uint8_t value to an register
Parameters
address uint8_t that contains the location of the register
value uint8_t that contains the value to write to the register
References IPASS::RF24L01::COMMAND::W_REGISTER, and write().
reset_arc()
void IPASS::RF24L01::reset_arc ()
resets the arc value to it's default value '0x03'
resets the arc value to it's default value '0x03' which means that the retransmit count is 3
References register_read(), register_write(), and IPASS::RF24L01::REGISTER::SETUP_RETR.
reset_ard()
void IPASS::RF24L01::reset_ard ()
resets the ard value to it's default value '0000'
resets the ard value to it's default value '0000' which means that the delay is 250 μS
References register_read(), register_write(), and IPASS::RF24L01::REGISTER::SETUP_RETR.
reset_aw()
void IPASS::RF24L01::reset_aw ()
resets the aw value to it's default value '11'
resets the aw value to it's default value '11' which means that an address is 5 bytes
References register_read(), register_write(), and IPASS::RF24L01::REGISTER::SETUP_AW.
reset_rf_pwr()
void IPASS::RF24L01::reset_rf_pwr ()
resets the rf_pwr value to it's default value '0x02'
resets the rf_pwr value to it's default value '0x02' which means that the RF output power in TX mode is 0 dBm
References register_read(), register_write(), and IPASS::RF24L01::REGISTER::RF_SETUP.
reset_RX_PW_P()
void IPASS::RF24L01::reset_RX_PW_P (const uint8_t & pipe)
resets the amount of bytes in RX_pipe
change the value in the specified pipe to 0 which means that the pipe is not used
Parameters
pipe value 0-5 that indicates which pipes value is changed
References register_write().
set_channel()
void IPASS::RF24L01::set_channel (uint8_t channel)
function to change the RF-channel of the RF24L01
Actuall RF-frequentie is 2400+value[MHz]
Parameters
channel the new channelvalue maximumvalue=128
References register_write(), and IPASS::RF24L01::REGISTER::RF_CH.
setting_disable()
void IPASS::RF24L01::setting_disable (SETTING::Setting registerFunction)
Function to enable a setting.
Function to disable a setting of the RF24L01
Parameters
registerFunction SETTING::Setting parameter that contains the register and mask of the setting
References IPASS::RF24L01::SETTING::Setting::Mask, IPASS::RF24L01::SETTING::Setting::REGISTER_ADDR, register_read(), and register_write().
setting_enable()
void IPASS::RF24L01::setting_enable (SETTING::Setting registerFunction)
Function to enable a setting.
Function to enable a setting of the RF24L01
Parameters
registerFunction SETTING::Setting parameter that contains the register and mask of the setting
References IPASS::RF24L01::SETTING::Setting::Mask, IPASS::RF24L01::SETTING::Setting::REGISTER_ADDR, register_read(), and register_write().
setting_read()
bool IPASS::RF24L01::setting_read (SETTING::Setting registerFunction)
Function to read the current status if a setting.
Function to read to current status of a setting of the RF24L01
Parameters
registerFunction SETTING::Setting parameter that contains the register, mask and the standardvalue of the setting
References IPASS::RF24L01::SETTING::Setting::Mask, IPASS::RF24L01::SETTING::Setting::REGISTER_ADDR, and register_read().
setting_reset()
void IPASS::RF24L01::setting_reset (SETTING::Setting registerFunction)
Function to reset a setting.
Function to reset a setting of the RF24L01
Parameters
registerFunction SETTING::Setting parameter that contains the register, mask and the standardvalue of the setting
References IPASS::RF24L01::SETTING::Setting::Reset_Value, setting_disable(), and setting_enable().
start_up()
void IPASS::RF24L01::start_up (std::array< uint8_t, 5 > RX_ADDR_P0, std::array< uint8_t, 5 > TX_ADDR, uint8_t channel, bool CRC, bool CRC_width, bool datarate) private
Startup function.
startup function that sets the value of RX_ADDR_P0, TX_ADDR, channel and CRC
References change_ADDR(), IPASS::RF24L01::SETTING::CRCO, IPASS::RF24L01::SETTING::EN_CRC, IPASS::RF24L01::SETTING::PWR_UP, IPASS::RF24L01::SETTING::RF_DR, IPASS::RF24L01::REGISTER::RX_ADDR_P0, set_channel(), setting_disable(), setting_enable(), and IPASS::RF24L01::REGISTER::TX_ADDR.
test()
bool IPASS::RF24L01::test ()
Test function.
Test function that tests reading and writing registers, writing payload, flushing payload and sending payload
Returns
returns true if pass and returns false in case of a fail. If it fails it sends an error message through the console
References IPASS::RF24L01::REGISTER::FIFO_STATUS, flush_rx_tx(), packet_send(), IPASS::RF24L01::SETTING::PWR_UP, register_read(), send_packages(), setting_enable(), IPASS::RF24L01::REGISTER::SETUP_AW, IPASS::RF24L01::REGISTER::STATUS, and write_tx().
write() [1/2]
template<size_t amount> void IPASS::RF24L01::write (const uint8_t & command, const std::array< uint8_t, amount > & value) inline private
Private write function.
Write function that writes the command and the values of a variabele size
Template Parameters
amount variabele that controls the size of std::array Data
Parameters
command uint8_t that contains the SPI-command
value std::array of uint8_t of variabel size
References bus, and minion_select.
write() [2/2]
void IPASS::RF24L01::write (const uint8_t & command, const uint8_t & value) private
Private write function.
Write function that writes the command and the value
Parameters
command uint8_t that contains the SPI-command
value uint8_t thats written after the SPI-command
References bus, and minion_select.
write_command()
void IPASS::RF24L01::write_command (const uint8_t & command)
Write one single command without value to the RF24L01.
Parameters
command uint8_t value to be written to the RF24L01
Warning
the commands are just mask and because of that they can not be used without some change so read datasheet before calling these commands you can crash your program by executing command without knowing what is does.
References IPASS::RF24L01::COMMAND::ACTIVATE, Active, bus, and minion_select.
write_tx()
template<size_t amount> void IPASS::RF24L01::write_tx (std::array< uint8_t, amount > & Data, bool no_ack = false) inline
Function to write data to TX_PLD.
The function does also always check if IRQ is active high and if thats true if resets IRQ to disable the lock
Template Parameters
amount variabele that controls the size of std::array Data
Parameters
Data std::array uint8_t that written to the TX_PLD register
no_ack boolean that controls if the data is written with or without acknowledgement
References IPASS::RF24L01::COMMAND::ACTIVATE, Active, IPASS::RF24L01::SETTING::EN_DYN_ACK, IRQ, register_write(), setting_disable(), setting_enable(), IPASS::RF24L01::REGISTER::STATUS, IPASS::RF24L01::COMMAND::W_TX_PAYLOAD, IPASS::RF24L01::COMMAND::W_TX_PAYLOAD_NO_ACK, write(), and write_command().
Member Data Documentation
Active
bool IPASS::RF24L01::Active = false private
boolean that indicates if the SPI-command Activate is active
The documentation for this class was generated from the following files:
Libraries/RF24L01/RF24L01.hpp
Libraries/RF24L01/RF24L01.cpp